language: ruby
rvm: 2.0.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - secure: "hvagymFxHfdKjZWVFz5Wz7MclCD/NeG0p9WaEeZIlKUoFPrt+PLJyNRd1a/mD1bxJhEjbNkpjBHxbcCDLCYoDna9IZF/EnIKLn+uoAzkiFbaM2CctvTzjBDUkrm4Lu08EOfxujR0refGtSZyRanw1Jm/JYTJqErmfVtZTRYqaJI="
    - GIT_COMMITTER_NAME=travis
    - GIT_COMMITTER_EMAIL=travis@example.com
    - GIT_AUTHOR_NAME=travis
    - GIT_AUTHOR_EMAIL=travis@example.com
